/*
 * Copyright (c) Effective Light 2015.
 * All rights reserved.
 */

package me.hamzaxx.fperms.shared.netty;

public enum ChangeType
{
    PLAYER_PREFIX, PLAYER_SUFFIX, GROUP_PREFIX, GROUP_SUFFIX, GROUP, PLAYER,
    SET_PLAYER_PERMISSION, UNSET_PLAYER_PERMISSION, RESET_PLAYER_PERMISSIONS,
    SET_GROUP_PERMISSION, UNSET_GROUP_PERMISSION, RESET_GROUP_PERMISSIONS,
}
